# Generated by Django 4.1.7 on 2023-03-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_totoalprice_order_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default-product-image.png', null=True, upload_to=''),
        ),
    ]
